"""Add organisation_name to users

Revision ID: 177f2cfde24b
Revises: 9c6667045117
Create Date: 2026-07-29 22:59:06.030170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '177f2cfde24b'
down_revision = '9c6667045117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organisation_name', sa.String(length=100), nullable=True))
        batch_op.drop_column('company')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organisation_name', sa.String(length=150), nullable=True))
        batch_op.drop_column('company_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sa.VARCHAR(length=150), nullable=True))
        batch_op.drop_column('organisation_name')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('organisation_name')

    # ### end Alembic commands ###
