"""Add company logo to users

Revision ID: 17aa873d1889
Revises: 70b0640a26c5
Create Date: 2026-08-22 16:29:00.882071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17aa873d1889'
down_revision = '70b0640a26c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organisation_logo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('organisation_logo')

    # ### end Alembic commands ###
