"""Add Cloudinary public ID to customer documents

Revision ID: 41d2eedf528d
Revises: 456aa81bf9bb
Create Date: 2026-08-12 00:11:03.595890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41d2eedf528d'
down_revision = '456aa81bf9bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cloudinary_public_id', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_documents', schema=None) as batch_op:
        batch_op.drop_column('cloudinary_public_id')

    # ### end Alembic commands ###
