"""Add password reset fields

Revision ID: 456aa81bf9bb
Revises: 1b1f3a2c27ae
Create Date: 2026-08-05 11:35:57.102575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '456aa81bf9bb'
down_revision = '1b1f3a2c27ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('customer_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.create_unique_constraint(
            'uq_customers_customer_code',
            ['customer_code']
        )

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_token_expiry')
        batch_op.drop_column('reset_token')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint(
            'uq_customers_customer_code',
            type_='unique'
        )
        batch_op.alter_column(
            'customer_code',
            existing_type=sa.VARCHAR(length=20),
            nullable=True
        )

    # ### end Alembic commands ###
