"""Add customer_code to customers

Revision ID: 609cc3b02e32
Revises: c88007923175
Create Date: 2026-07-19 20:36:49.580940
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "609cc3b02e32"
down_revision = "c88007923175"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("customers", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("customer_code", sa.String(length=20), nullable=True)
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("customers", schema=None) as batch_op:
        batch_op.drop_column("customer_code")
    # ### end Alembic commands ###