"""Add Cloudinary resource type to customer documents

Revision ID: 70b0640a26c5
Revises: 41d2eedf528d
Create Date: 2026-08-13 23:16:40.655018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70b0640a26c5'
down_revision = '41d2eedf528d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cloudinary_resource_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_documents', schema=None) as batch_op:
        batch_op.drop_column('cloudinary_resource_type')

    # ### end Alembic commands ###
