"""Added organisation profile fields

Revision ID: 9c6667045117
Revises: 04fe5380f625
Create Date: 2026-07-27 01:26:20.274490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c6667045117'
down_revision = '04fe5380f625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organisation_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('business_phone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('business_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('business_address', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('website')
        batch_op.drop_column('business_address')
        batch_op.drop_column('business_email')
        batch_op.drop_column('business_phone')
        batch_op.drop_column('organisation_name')

    # ### end Alembic commands ###
