"""Add created_at to customers

Revision ID: bb6d8f9fd8e9
Revises: 6f3427e5d3de
Create Date: 2026-07-16 19:46:36.270677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb6d8f9fd8e9'
down_revision = '6f3427e5d3de'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column(
        "customers",
    sa.Column(
        "created_at",
        sa.DateTime(),
        nullable=True
    )
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
