"""Add subscription fields

Revision ID: ce32f30ed1ea
Revises: efd09ded9b1a
Create Date: 2026-09-01 15:09:49.104450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce32f30ed1ea'
down_revision = 'efd09ded9b1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_status',sa.String(length=20),nullable=False,server_default='TRIAL'))
        batch_op.add_column(sa.Column('trial_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('trial_ends_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('subscription_plan', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('billing_period', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('subscription_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('subscription_ends_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
        

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('stripe_subscription_id')
        batch_op.drop_column('stripe_customer_id')
        batch_op.drop_column('subscription_ends_at')
        batch_op.drop_column('subscription_started_at')
        batch_op.drop_column('billing_period')
        batch_op.drop_column('subscription_plan')
        batch_op.drop_column('trial_ends_at')
        batch_op.drop_column('trial_started_at')
        batch_op.drop_column('subscription_status')

    # ### end Alembic commands ###
